BEGIN TRANSACTION;
DROP TABLE IF EXISTS "alternativa";
CREATE TABLE IF NOT EXISTS "alternativa" (
	"id_alternativa"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"alternativa"	TEXT NOT NULL
);
INSERT INTO "alternativa" VALUES (1,'Apenas I. ');
INSERT INTO "alternativa" VALUES (2,'Apenas II. ');
INSERT INTO "alternativa" VALUES (3,'Apenas III. ');
INSERT INTO "alternativa" VALUES (4,'Apenas I e II.');
INSERT INTO "alternativa" VALUES (5,'Apenas II e III. ');
INSERT INTO "alternativa" VALUES (6,'quinta forma normal (5FN).');
INSERT INTO "alternativa" VALUES (7,'primeira forma normal (1FN).');
INSERT INTO "alternativa" VALUES (8,'segunda forma normal (2FN).');
INSERT INTO "alternativa" VALUES (9,'terceira forma normal (3FN).');
INSERT INTO "alternativa" VALUES (10,'quarta forma normal (4FN).');
INSERT INTO "alternativa" VALUES (11,'3FN');
INSERT INTO "alternativa" VALUES (12,'2FN');
INSERT INTO "alternativa" VALUES (13,'1FN');
INSERT INTO "alternativa" VALUES (14,'1FN e 2FN');
INSERT INTO "alternativa" VALUES (15,'2FN e 3FN');
INSERT INTO "alternativa" VALUES (16,'abstração. ');
INSERT INTO "alternativa" VALUES (17,'acoplamento.');
INSERT INTO "alternativa" VALUES (18,'encapsulamento.');
INSERT INTO "alternativa" VALUES (19,'herança. ');
INSERT INTO "alternativa" VALUES (20,'polimorfismo. ');
INSERT INTO "alternativa" VALUES (21,'Carlos é um objeto. Tem como métodos andar, correr e pular e, ter 25 anos, ser casado e trabalhar com TICs são variáveis ou estados. ');
INSERT INTO "alternativa" VALUES (22,'Andar, correr e pular, são objetos que podem ter como variável Carlos. ');
INSERT INTO "alternativa" VALUES (23,'Carlos é uma classe pois há outros Carlos que têm idade diferente de 25 anos e que exercem outras profissões. ');
INSERT INTO "alternativa" VALUES (24,'Ter 25 anos, ser casado, andar e correr são estados que podem ser associados ao objeto Carlos. ');
INSERT INTO "alternativa" VALUES (25,'Define habilidades e comportamentos de um objeto.');
INSERT INTO "alternativa" VALUES (26,'É uma chamada a um objeto para invocar um de seus métodos, ativando um comportamento descrito por sua classe.');
INSERT INTO "alternativa" VALUES (27,'É a habilidade de concentrar nos aspectos essenciais de um contexto qualquer, ignorando características menos importantes ou acidentais.');
INSERT INTO "alternativa" VALUES (28,'É um mecanismo onde uma classe pode estender uma outra classe, aproveitando seus métodos e atributos.');
INSERT INTO "alternativa" VALUES (29,'Este mecanismo é utilizado para impedir o acesso direto aos atributos de um objeto, disponibilizando externamente apenas os métodos que alteram estes atributos.');
INSERT INTO "alternativa" VALUES (30,'conter métodos implementados.');
INSERT INTO "alternativa" VALUES (31,'ser instanciada diretamente.');
INSERT INTO "alternativa" VALUES (32,' possuir um único construtor vazio.');
INSERT INTO "alternativa" VALUES (33,'possuir métodos abstratos.');
INSERT INTO "alternativa" VALUES (34,'conter variáveis e métodos privados.');
INSERT INTO "alternativa" VALUES (35,'Enterprise Business Solutions');
INSERT INTO "alternativa" VALUES (36,'Embarcadero Delphi');
INSERT INTO "alternativa" VALUES (37,'Eclipises');
INSERT INTO "alternativa" VALUES (38,'Komodu');
INSERT INTO "alternativa" VALUES (39,'Abstração - Encapsulamento - Concretização - Modelagem');
INSERT INTO "alternativa" VALUES (40,'Estruturação - Modulorização - Concretização - Modelagem');
INSERT INTO "alternativa" VALUES (41,'Estruturação - Modulorização - Herança - Polimorfismo');
INSERT INTO "alternativa" VALUES (42,'Abstração - Encapsulamento - Herança - Polimorfismo');
INSERT INTO "alternativa" VALUES (43,'Failback é o processo no qual uma máquina assume os serviços de outra quando esta apresenta alguma falha.');
INSERT INTO "alternativa" VALUES (44,'Dependendo da natureza do serviço, executar uma operação de failover significa interromper as transações em andamento, perdendo-as, sendo necessário reiniciá-las após o término do processo');
INSERT INTO "alternativa" VALUES (45,'A principal diferença entre clusters assimétricos e simétricos é que no cluster simétrico há a figura de um servidor inativo aguardando uma falha de outro.');
INSERT INTO "alternativa" VALUES (46,'sendo que cada nó exerce o controle sobre seu nó vizinho e o último nó exercerá o controle sobre o primeiro nó.');
INSERT INTO "alternativa" VALUES (47,'sendo que cada nó exerce seu próprio controle.');
INSERT INTO "alternativa" VALUES (48,'controlados por um computador principal.');
INSERT INTO "alternativa" VALUES (49,'Caso seja definido que cada servidor utilizará apenas os seus próprios discos, os dados não precisam ser copiados entre os sistemas.');
INSERT INTO "alternativa" VALUES (50,'O servidor secundário também pode ser usado para o processamento de outras operações no sistema, além da função de assumir o processamento no caso de falha do servidor primário.');
INSERT INTO "alternativa" VALUES (51,'Mesmo quando cada servidor usa apenas os seus próprios discos, o método secundário ativo não exige o gerenciamento do equilíbrio, entre os servidores, das requisições vindas dos clientes.');
INSERT INTO "alternativa" VALUES (52,'Um caminho deve iniciar e terminar por um lugar.');
INSERT INTO "alternativa" VALUES (53,'Uma transição dispara quando alguma de suas entradas possui uma marcação (token).');
INSERT INTO "alternativa" VALUES (54,'Quando uma transição dispara, ela consome uma marcação (token) de cada uma das suas entradas e gera uma para cada saída.');
INSERT INTO "alternativa" VALUES (55,'A computação paralela é caracterizada pelo uso de vários processadores para executar uma computação de forma mais rápida, baseando-se no fato de que o processo de resolução de um problema pode ser dividido em tarefas menores, que podem ser realizadas simultaneamente através de algum tipo de coordenação.');
INSERT INTO "alternativa" VALUES (56,'A execução de tarefas em um ambiente de processadores distribuídos com acoplamento fraco prevê que a memória seja compartilhada entre os processos trabalhadores.');
INSERT INTO "alternativa" VALUES (57,'Em programação paralela não é necessário se conhecer a arquitetura de comunicação entre processadores para elaborar os programas.');
INSERT INTO "alternativa" VALUES (58,'Um sistema distribuído fracamente acoplado permite que máquinas e usuários do ambiente sejam fundamentalmente independentes, bem como a interação de forma limitada, quando isto for necessário, compartilhando recursos como discos e impressoras, entre outros.');
INSERT INTO "alternativa" VALUES (59,'O modelo de computação distribuída Peer-to-Peer é uma tecnologia que estabelece uma espécie de rede virtual de computadores, onde cada estação tem capacidades e responsabilidades equivalentes.');
INSERT INTO "alternativa" VALUES (60,'Uma vantagem dos sistemas distribuídos sobre os sistemas centralizados é a disponibilidade de software para este tipo de ambiente.');
COMMIT;
